wandb_version: 1

architecture:
  desc: null
  value: resnet50
dataset:
  desc: null
  value: imagenet
epochs:
  desc: null
  value: 50
num_classes:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.9.9
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713235738.396842
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.9
      5: 0.15.9
      8:
      - 3
      - 5
